package demo.geographical.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import demo.geographical.pojo.po.GeographicalArea;
import demo.geographical.pojo.po.example.GeographicalAreaExample;

public interface GeographicalAreaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geographical_area
	 * @mbg.generated
	 */
	long countByExample(GeographicalAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geographical_area
	 * @mbg.generated
	 */
	int deleteByExample(GeographicalAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geographical_area
	 * @mbg.generated
	 */
	int insert(GeographicalArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geographical_area
	 * @mbg.generated
	 */
	int insertSelective(GeographicalArea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geographical_area
	 * @mbg.generated
	 */
	List<GeographicalArea> selectByExample(GeographicalAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geographical_area
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") GeographicalArea record,
			@Param("example") GeographicalAreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table geographical_area
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") GeographicalArea record, @Param("example") GeographicalAreaExample example);
}