# bbt

server:
  port: 10002
    
spring:
  application:
    name: bbt
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
endpoints:
  shutdown:
    enabled: true
    

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    # demo.test.controller: DEBUG
    demo.test.mapper: DEBUG
    demo.tool.mapper: DEBUG
    # demo.mapper: DEBUG
    # demo.base.system.mapper: DEBUG
    demo.base.user.mapper: DEBUG
    demo.autoTestBase.testEvent.mapper: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%p] [%d{yyyy-MM-dd HH:mm:ss}][%c]%m%n [%thread] %-5level %logger{36}"
      
  file.name: /home/u10/logs/bbt.log