# bbt

server:
  port: 10002
    
spring:
  application:
    name: bbt
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    bbt:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bbt?characterEncoding=utf8&useUnicode=true&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false&useServerPrepStmts=true&allowMultiQueries=true
      username: root
      password: test
    cx:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/financeclear?characterEncoding=utf8&useUnicode=true&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false&useServerPrepStmts=true&allowMultiQueries=true
      username: root
      password: test
  redis:
    database: 0
    host: 127.0.0.1
    port: 6381
    password: 
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 2000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    username: u1
    password: something
    
endpoints:
  shutdown:
    enabled: true
    
optionFilePath:
  system: "/home/u2/bbt/optionFile/system/option.json"
  automationTest: "/home/u2/bbt/optionFile/automationTest/option.json"

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    # demo.test.controller: DEBUG
    demo.test.mapper: DEBUG
    demo.tool.mapper: DEBUG
    # demo.mapper: DEBUG
    # demo.base.system.mapper: DEBUG
    demo.base.user.mapper: DEBUG
    demo.autoTestBase.testEvent.mapper: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%p] [%d{yyyy-MM-dd HH:mm:ss}][%c]%m%n [%thread] %-5level %logger{36}"
      
  file.name: /home/u2/logs/bbt.log