# ssms
    
server:
  port: 10001

spring:
  application:
    name: cdm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/financeclear?characterEncoding=utf8&useUnicode=true&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false&useServerPrepStmts=true&allowMultiQueries=true
    username: root
    password: test
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 2000
  # mvc:
  #   view:
  #     prefix: /jsp/
  #     suffix: .jsp

#mybatis:
  #typeAliasesPackage: demo.domain, demo.*.domain, demo.account_holder.domain, demo.account_info.domain, demo.bank.domain, demo.trading.domain, demo.base.user.domain, demo.base.base.domain, demo.article.domain, demo.articleComment.domain, demo.vcode.domain

envName: dev

logging:
  level:
    org.springframework.web: DEBUG
    # demo.test.controller: DEBUG
    demo.test.mapper: DEBUG
    demo.tool.mapper: DEBUG
    # demo.mapper: DEBUG
    # demo.base.system.mapper: DEBUG
    demo.base.user.mapper: DEBUG
    # demo.organizations.mapper: DEBUG
    # demo.mobile.mapper: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "[%p] [%d{yyyy-MM-dd HH:mm:ss}][%c]%m%n [%thread] %-5level %logger{36}"
      
  file: /home/u1/logs/bbt.log