package demo.geographical.pojo.po;

import java.util.Date;

public class GeographicalArea {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column geographical_area.id
	 * 
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column geographical_area.create_time
	 * 
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column geographical_area.area_name
	 * 
	 * @mbg.generated
	 */
	private String areaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column geographical_area.area_type
	 * 
	 * @mbg.generated
	 */
	private Integer areaType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column geographical_area.belong_to
	 * 
	 * @mbg.generated
	 */
	private Long belongTo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column geographical_area.id
	 * 
	 * @return the value of geographical_area.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column geographical_area.id
	 * 
	 * @param id the value for geographical_area.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column geographical_area.create_time
	 * 
	 * @return the value of geographical_area.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column geographical_area.create_time
	 * 
	 * @param createTime the value for geographical_area.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column geographical_area.area_name
	 * 
	 * @return the value of geographical_area.area_name
	 * @mbg.generated
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column geographical_area.area_name
	 * 
	 * @param areaName the value for geographical_area.area_name
	 * @mbg.generated
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName == null ? null : areaName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column geographical_area.area_type
	 * 
	 * @return the value of geographical_area.area_type
	 * @mbg.generated
	 */
	public Integer getAreaType() {
		return areaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column geographical_area.area_type
	 * 
	 * @param areaType the value for geographical_area.area_type
	 * @mbg.generated
	 */
	public void setAreaType(Integer areaType) {
		this.areaType = areaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column geographical_area.belong_to
	 * 
	 * @return the value of geographical_area.belong_to
	 * @mbg.generated
	 */
	public Long getBelongTo() {
		return belongTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column geographical_area.belong_to
	 * 
	 * @param belongTo the value for geographical_area.belong_to
	 * @mbg.generated
	 */
	public void setBelongTo(Long belongTo) {
		this.belongTo = belongTo;
	}

	@Override
	public String toString() {
		return "GeographicalArea [id=" + id + ", createTime=" + createTime + ", areaName=" + areaName + ", areaType="
				+ areaType + ", belongTo=" + belongTo + "]";
	}

}